services:
  app:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    deploy:
      resources:
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
    environment:
      - DATABASE_URL
      - PASSAGE_APP_ID
      - PASSAGE_API_KEY
      - JWT_SECRET_KEY
